from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe394cb06589'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_info')),
    schema='stocksight'
    )
    op.create_index('idx_company_country', 'company_info', ['country'], unique=False, schema='stocksight')
    op.create_index('idx_company_sector', 'company_info', ['sector'], unique=False, schema='stocksight')
    op.create_index(op.f('ix_stocksight_company_info_symbol'), 'company_info', ['symbol'], unique=True, schema='stocksight')
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchanges')),
    schema='stocksight'
    )
    op.create_index('idx_exchange_country', 'exchanges', ['country'], unique=False, schema='stocksight')
    op.create_index(op.f('ix_stocksight_exchanges_code'), 'exchanges', ['code'], unique=True, schema='stocksight')
    op.create_table('stock_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_prices')),
    schema='stocksight'
    )
    op.create_index('idx_stock_price_symbol_timestamp', 'stock_prices', ['symbol', 'timestamp'], unique=False, schema='stocksight')
    op.create_index(op.f('ix_stocksight_stock_prices_symbol'), 'stock_prices', ['symbol'], unique=False, schema='stocksight')
    op.create_table('dividend_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stocksight.company_info.symbol'], name=op.f('fk_dividend_history_symbol_company_info')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dividend_history')),
    schema='stocksight'
    )
    op.create_index('idx_dividend_symbol_date', 'dividend_history', ['symbol', 'date'], unique=False, schema='stocksight')
    op.create_index(op.f('ix_stocksight_dividend_history_symbol'), 'dividend_history', ['symbol'], unique=False, schema='stocksight')
    op.create_table('stock_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('ratio', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stocksight.company_info.symbol'], name=op.f('fk_stock_splits_symbol_company_info')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_splits')),
    schema='stocksight'
    )
    op.create_index('idx_split_symbol_date', 'stock_splits', ['symbol', 'date'], unique=False, schema='stocksight')
    op.create_index(op.f('ix_stocksight_stock_splits_symbol'), 'stock_splits', ['symbol'], unique=False, schema='stocksight')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocksight_stock_splits_symbol'), table_name='stock_splits', schema='stocksight')
    op.drop_index('idx_split_symbol_date', table_name='stock_splits', schema='stocksight')
    op.drop_table('stock_splits', schema='stocksight')
    op.drop_index(op.f('ix_stocksight_dividend_history_symbol'), table_name='dividend_history', schema='stocksight')
    op.drop_index('idx_dividend_symbol_date', table_name='dividend_history', schema='stocksight')
    op.drop_table('dividend_history', schema='stocksight')
    op.drop_index(op.f('ix_stocksight_stock_prices_symbol'), table_name='stock_prices', schema='stocksight')
    op.drop_index('idx_stock_price_symbol_timestamp', table_name='stock_prices', schema='stocksight')
    op.drop_table('stock_prices', schema='stocksight')
    op.drop_index(op.f('ix_stocksight_exchanges_code'), table_name='exchanges', schema='stocksight')
    op.drop_index('idx_exchange_country', table_name='exchanges', schema='stocksight')
    op.drop_table('exchanges', schema='stocksight')
    op.drop_index(op.f('ix_stocksight_company_info_symbol'), table_name='company_info', schema='stocksight')
    op.drop_index('idx_company_sector', table_name='company_info', schema='stocksight')
    op.drop_index('idx_company_country', table_name='company_info', schema='stocksight')
    op.drop_table('company_info', schema='stocksight')
    # ### end Alembic commands ###
