from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff21e9c24c9c'
down_revision = 'insert_biotech_competitors'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_dividend_history_symbol_company_info', 'dividend_history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_dividend_history_symbol_company_info'), 'dividend_history', 'company_info', ['symbol'], ['symbol'], source_schema='stocksight', referent_schema='stocksight')
    op.drop_constraint('fk_stock_splits_symbol_company_info', 'stock_splits', type_='foreignkey')
    op.create_foreign_key(op.f('fk_stock_splits_symbol_company_info'), 'stock_splits', 'company_info', ['symbol'], ['symbol'], source_schema='stocksight', referent_schema='stocksight')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_stock_splits_symbol_company_info'), 'stock_splits', schema='stocksight', type_='foreignkey')
    op.create_foreign_key('fk_stock_splits_symbol_company_info', 'stock_splits', 'company_info', ['symbol'], ['symbol'])
    op.drop_constraint(op.f('fk_dividend_history_symbol_company_info'), 'dividend_history', schema='stocksight', type_='foreignkey')
    op.create_foreign_key('fk_dividend_history_symbol_company_info', 'dividend_history', 'company_info', ['symbol'], ['symbol'])
    # ### end Alembic commands ###
